### PR TITLE
Fix is_logging column of the aws_cloudtrail_trail table returns null when value is 'true' in the AWS CLI closes #957

### LINKED ISSUE #957: Fix is_logging column of the `aws_cloudtrail_trail table` returns null when value is 'true' in the AWS CLI
**Describe the bug**
The is_logging column of the `aws_cloudtrail_trail table` returns null when the value is 'true' in the AWS CLI

**Steampipe version (`steampipe -v`)**
Example: v0.13.6

**Plugin version (`steampipe plugin list`)**
Example: v0.56.0

**To reproduce**
run `select * from aws_cloudtrail_trail`, or a more targeted query to pull back information about whether a cloudtrail is currently logging, and compare that data to AWS CLI output or console information. Here's an example CLI command `aws cloudtrail get-trail-status --name MyTargetTrail --region us-east-1`

**Expected behavior**
The value from the AWS CLI and the Steampipe CLI should remain consistent.

**Additional context**
```
 select * from aws_cloudtrail_trail limit 1
[
 {
  "_ctx": {
   "connection_name": "default"
  },
  "account_id": "xxxxxxxxxxxx",
  "advanced_event_selectors": null,
  "akas": [
   "arn:aws:cloudtrail:us-east-1:xxxxxxxxx:trail/turbot-xxxxxxxx-us-east-1-trail"
  ],
  "arn": "arn:aws:cloudtrail:us-east-1:xxxxxxx:trail/turbot-xxxxxxx-us-east-1-trail",
  "cloudwatch_logs_role_arn": null,
  "event_selectors": null,
  "has_custom_event_selectors": false,
  "has_insight_selectors": false,
  "home_region": "us-east-1",
  "include_global_service_events": true,
  "insight_selectors": null,
  "is_logging": null,
  "is_multi_region_trail": true,
  "is_organization_trail": false,
  "kms_key_id": null,
  "latest_cloudwatch_logs_delivery_error": null,
  "latest_cloudwatch_logs_delivery_time": null,
  "latest_delivery_error": null,
  "latest_delivery_time": null,
  "latest_digest_delivery_error": null,
  "latest_digest_delivery_time": null,
  "latest_notification_error": null,
  "latest_notification_time": null,
  "log_file_validation_enabled": true,
  "log_group_arn": null,
  "name": "turbot-xxxxxxxxx-us-east-1-trail",
  "partition": "aws",
  "region": "us-west-1",
  "s3_bucket_name": "turbot-xxxxxxxx-us-east-1",
  "s3_key_prefix": null,
  "sns_topic_arn": null,
  "start_logging_time": null,
  "stop_logging_time": null,
  "tags": {},
  "tags_src": [],
  "title": "turbot-xxxxxxx-us-east-1-trail"
 }
]
```

AWS CLI Response :
```
{
    "IsLogging": true,
    "LatestDeliveryTime": "2022-04-25T19:04:29.220000+05:30",
    "StartLoggingTime": "2021-06-24T17:39:54.561000+05:30",
    "LatestDigestDeliveryTime": "2022-04-25T18:31:30.255000+05:30",
    "LatestDeliveryAttemptTime": "2022-04-25T13:34:29Z",
    "LatestNotificationAttemptTime": "",
    "LatestNotificationAttemptSucceeded": "",
    "LatestDeliveryAttemptSucceeded": "2022-04-25T13:34:29Z",
    "TimeLoggingStarted": "2021-06-24T12:09:54Z",
    "TimeLoggingStopped": ""
}

```

### PR DESCRIPTION
**Pull request by ParthaI**
# Integration test logs
<details>
  <summary>Logs</summary>
  
```
No env file present for the current environment:  staging 
 Falling back to .env config
No env file present for the current environment:  staging
customEnv TURBOT_TEST_EXPECTED_TIMEOUT undefined

SETUP: tests/aws_cloudtrail_trail []

PRETEST: tests/aws_cloudtrail_trail

TEST: tests/aws_cloudtrail_trail
Running terraform
data.aws_region.alternate: Refreshing state...
data.aws_region.primary: Refreshing state...
data.aws_caller_identity.current: Refreshing state...
data.aws_partition.current: Refreshing state...
data.null_data_source.resource: Refreshing state...
aws_s3_bucket.named_test_resource: Creating...
aws_s3_bucket.named_test_resource: Creation complete after 7s [id=turbottest82533]
aws_cloudtrail.named_test_resource: Creating...
aws_cloudtrail.named_test_resource: Creation complete after 5s [id=turbottest82533]

Warning: Deprecated Resource

  on variables.tf line 44, in data "null_data_source" "resource":
  44: data "null_data_source" "resource" {

The null_data_source was historically used to construct intermediate values to
re-use elsewhere in configuration, the same can now be achieved using locals


Warning: Argument is deprecated

  on variables.tf line 76, in resource "aws_s3_bucket" "named_test_resource":
  76:   policy = <<POLICY
  77: {
  78:     "Version": "2012-10-17",
  79:     "Statement": [
  80:         {
  81:             "Sid": "AWSCloudTrailAclCheck",
  82:             "Effect": "Allow",
  83:             "Principal": {
  84:               "Service": "cloudtrail.amazonaws.com"
  85:             },
  86:             "Action": "s3:GetBucketAcl",
  87:             "Resource": "arn:aws:s3:::${var.resource_name}"
  88:         },
  89:         {
  90:             "Sid": "AWSCloudTrailWrite",
  91:             "Effect": "Allow",
  92:             "Principal": {
  93:               "Service": "cloudtrail.amazonaws.com"
  94:             },
  95:             "Action": "s3:PutObject",
  96:             "Resource": "arn:aws:s3:::${var.resource_name}/prefix/AWSLogs/${data.aws_caller_identity.current.account_id}/*",
  97:             "Condition": {
  98:                 "StringEquals": {
  99:                     "s3:x-amz-acl": "bucket-owner-full-control"
 100:                 }
 101:             }
 102:         }
 103:     ]
 104: }
 105: POLICY

Use the aws_s3_bucket_policy resource instead


Apply complete! Resources: 2 added, 0 changed, 0 destroyed.

Outputs:

account_id = 987902158475
aws_partition = aws
region_name = us-east-1
resource_aka = arn:aws:cloudtrail:us-east-1:987902158475:trail/turbottest82533
resource_name = turbottest82533

Running SQL query: test-get-query.sql
[
  {
    "arn": "arn:aws:cloudtrail:us-east-1:987902158475:trail/turbottest82533",
    "has_custom_event_selectors": true,
    "has_insight_selectors": false,
    "home_region": "us-east-1",
    "include_global_service_events": false,
    "is_multi_region_trail": false,
    "is_organization_trail": false,
    "log_file_validation_enabled": false,
    "name": "turbottest82533",
    "s3_bucket_name": "turbottest82533",
    "s3_key_prefix": "prefix"
  }
]
✔ PASSED

Running SQL query: test-hydrate-query.sql
[
  {
    "event_selectors": [
      {
        "DataResources": [
          {
            "Type": "AWS::Lambda::Function",
            "Values": [
              "arn:aws:lambda"
            ]
          }
        ],
        "ExcludeManagementEventSources": [],
        "IncludeManagementEvents": true,
        "ReadWriteType": "All"
      }
    ],
    "is_logging": true,
    "tags_src": [
      {
        "Key": "name",
        "Value": "turbottest82533"
      }
    ]
  }
]
✔ PASSED

Running SQL query: test-list-call-query.sql
[
  {
    "arn": "arn:aws:cloudtrail:us-east-1:987902158475:trail/turbottest82533",
    "name": "turbottest82533"
  }
]
✔ PASSED

Running SQL query: test-turbot-query.sql
[
  {
    "akas": [
      "arn:aws:cloudtrail:us-east-1:987902158475:trail/turbottest82533"
    ],
    "tags": {
      "name": "turbottest82533"
    },
    "title": "turbottest82533"
  }
]
✔ PASSED

POSTTEST: tests/aws_cloudtrail_trail

TEARDOWN: tests/aws_cloudtrail_trail

SUMMARY:

1/1 passed.
```
</details>

# Example query results
<details>
  <summary>Results</summary>
  
```
> select * from aws.aws_cloudtrail_trail where name = 'turbot-987902158475-us-east-1-trail'
+-------------------------------------+-------------------------------------------------------------------------------------+-------------+-----------------------+-----------------------------+---------
| name                                | arn                                                                                 | home_region | is_multi_region_trail | log_file_validation_enabled | is_loggi
+-------------------------------------+-------------------------------------------------------------------------------------+-------------+-----------------------+-----------------------------+---------
| turbot-987902158475-us-east-1-trail | arn:aws:cloudtrail:us-east-1:987902158475:trail/turbot-987902158475-us-east-1-trail | us-east-1   | true                  | true                        | true    
+-------------------------------------+-------------------------------------------------------------------------------------+-------------+-----------------------+-----------------------------+---------
> select * from aws.aws_cloudtrail_trail
+-------------------------------------+-------------------------------------------------------------------------------------+-------------+-----------------------+-----------------------------+---------
| name                                | arn                                                                                 | home_region | is_multi_region_trail | log_file_validation_enabled | is_loggi
+-------------------------------------+-------------------------------------------------------------------------------------+-------------+-----------------------+-----------------------------+---------
| turbot-987902158475-us-east-1-trail | arn:aws:cloudtrail:us-east-1:987902158475:trail/turbot-987902158475-us-east-1-trail | us-east-1   | true                  | true                        | true    
| turbot-987902158475-us-east-1-trail | arn:aws:cloudtrail:us-east-1:987902158475:trail/turbot-987902158475-us-east-1-trail | us-east-1   | true                  | true                        | true    
| turbot-987902158475-us-east-1-trail | arn:aws:cloudtrail:us-east-1:987902158475:trail/turbot-987902158475-us-east-1-trail | us-east-1   | true                  | true                        | true    
| turbot-987902158475-us-east-1-trail | arn:aws:cloudtrail:us-east-1:987902158475:trail/turbot-987902158475-us-east-1-trail | us-east-1   | true                  | true                        | true    
| turbot-987902158475-us-east-1-trail | arn:aws:cloudtrail:us-east-1:987902158475:trail/turbot-987902158475-us-east-1-trail | us-east-1   | true                  | true                        | true    
| turbot-987902158475-us-east-1-trail | arn:aws:cloudtrail:us-east-1:987902158475:trail/turbot-987902158475-us-east-1-trail | us-east-1   | true                  | true                        | true    
| turbot-987902158475-us-east-1-trail | arn:aws:cloudtrail:us-east-1:987902158475:trail/turbot-987902158475-us-east-1-trail | us-east-1   | true                  | true                        | true    
| turbot-987902158475-us-east-1-trail | arn:aws:cloudtrail:us-east-1:987902158475:trail/turbot-987902158475-us-east-1-trail | us-east-1   | true                  | true                        | true    
| turbot-987902158475-us-east-1-trail | arn:aws:cloudtrail:us-east-1:987902158475:trail/turbot-987902158475-us-east-1-trail | us-east-1   | true                  | true                        | true    
| turbot-987902158475-us-east-1-trail | arn:aws:cloudtrail:us-east-1:987902158475:trail/turbot-987902158475-us-east-1-trail | us-east-1   | true                  | true                        | true    
| turbot-987902158475-us-east-1-trail | arn:aws:cloudtrail:us-east-1:987902158475:trail/turbot-987902158475-us-east-1-trail | us-east-1   | true                  | true                        | true    
| turbot-987902158475-us-east-1-trail | arn:aws:cloudtrail:us-east-1:987902158475:trail/turbot-987902158475-us-east-1-trail | us-east-1   | true                  | true                        | true    
| turbot-987902158475-us-east-1-trail | arn:aws:cloudtrail:us-east-1:987902158475:trail/turbot-987902158475-us-east-1-trail | us-east-1   | true                  | true                        | true    
| turbot-987902158475-us-east-1-trail | arn:aws:cloudtrail:us-east-1:987902158475:trail/turbot-987902158475-us-east-1-trail | us-east-1   | true                  | true                        | true    
| turbot-987902158475-us-east-1-trail | arn:aws:cloudtrail:us-east-1:987902158475:trail/turbot-987902158475-us-east-1-trail | us-east-1   | true                  | true                        | true    
| turbot-987902158475-us-east-1-trail | arn:aws:cloudtrail:us-east-1:987902158475:trail/turbot-987902158475-us-east-1-trail | us-east-1   | true                  | true                        | true    
| turbot-987902158475-us-east-1-trail | arn:aws:cloudtrail:us-east-1:987902158475:trail/turbot-987902158475-us-east-1-trail | us-east-1   | true                  | true                        | true    
+-------------------------------------+-------------------------------------------------------------------------------------+-------------+-----------------------+-----------------------------+---------
> select * from aws.aws_cloudtrail_trail where name = 'turbot-2746584'
+------+-----+-------------+-----------------------+-----------------------------+------------+---------------+--------------------------+----------------------------+-----------------------+-----------
| name | arn | home_region | is_multi_region_trail | log_file_validation_enabled | is_logging | log_group_arn | cloudwatch_logs_role_arn | has_custom_event_selectors | has_insight_selectors | include_gl
+------+-----+-------------+-----------------------+-----------------------------+------------+---------------+--------------------------+----------------------------+-----------------------+-----------
+------+-----+-------------+-----------------------+-----------------------------+------------+---------------+--------------------------+----------------------------+-----------------------+-----------

```
</details>

### CODE REVIEW

**Review by misraved — APPROVED** [review]

**Comment by dito-ab** [comment]
Hi, is this PR context also fix for cloudtrail that activate from AWS organization? because i check the value is still null
image

**Comment by misraved** [comment]
Thanks @dito-ab for pointing out that the issue exists for organization trails. The fix was intended for multi-regional shadow trails.

Sorry to see that the issue persists for the organization trails, we will try to reproduce it and push in a fix.

**Comment by misraved** [comment]
@dito-ab we have managed to reproduce the error. Thanks for catching the issue 👍 . 

Since this PR was only in the context of multi-regional shadow trails, we have created a new [issue](https://github.com/turbot/steampipe-plugin-aws/issues/1068) to keep a track of the fix for organizational trails.

**Comment by dito-ab** [comment]
Great, Thank you  :+1:

**Pull request merged**
