### PR TITLE
Add EKS Insight table

### PR DESCRIPTION
**Pull request by Zlender**
In order for this to work EKS go sdk need to be updated to latest version. I wasn't sure if it should be part of this PR or separate.
# Integration test logs
<details>
  <summary>Logs</summary>

```
Add passing integration test logs here
```
</details>

# Example query results
<details>
  <summary>Results</summary>

```
select
  id,
  name,
  cluster_name
  description,
  insight_status,
  recommendation
from
  aws_eks_insight;
```
</details>

### CODE REVIEW

**Comment by misraved** [comment]
Welcome to Steampipe @Zlender and thank you so much for opening a PR for this new table 👍.

**Comment by misraved** [comment]
@Zlender you can include the update to the AWS SDK in this PR itself.

**Comment by Zlender** [comment]
@misraved I am worried that it brings so many changes that it would overload this PR. The diff with updated all AWS libraries includes all these files to get it back running
```
	modified:   aws/table_aws_cognito_identity_pool.go
	modified:   aws/table_aws_cognito_user_pool.go
	modified:   aws/table_aws_guardduty_detector.go
	modified:   aws/table_aws_guardduty_filter.go
	modified:   aws/table_aws_guardduty_finding.go
	modified:   aws/table_aws_guardduty_ipset.go
	modified:   aws/table_aws_guardduty_member.go
	modified:   aws/table_aws_guardduty_publishing_destination.go
	modified:   aws/table_aws_guardduty_threat_intel_set.go
	modified:   aws/table_aws_lambda_layer_version.go
	modified:   aws/table_aws_macie2_classification_job.go
	modified:   aws/table_aws_mgn_application.go
	modified:   aws/table_aws_msk_cluster.go
	modified:   aws/table_aws_s3_account_settings.go
	modified:   aws/table_aws_s3_bucket.go
	modified:   aws/table_aws_s3_object.go
	modified:   aws/table_aws_securityhub_action_target.go
	modified:   aws/table_aws_securityhub_finding.go
	modified:   aws/table_aws_securityhub_finding_aggregator.go
	modified:   aws/table_aws_securityhub_insight.go
	modified:   aws/table_aws_securityhub_member.go
	modified:   aws/table_aws_securityhub_product.go
	modified:   aws/table_aws_securityhub_standards_control.go
	modified:   aws/table_aws_securityhub_standards_subscription.go
	modified:   aws/table_aws_securitylake_data_lake.go
	modified:   aws/table_aws_securitylake_subscriber.go
	modified:   aws/table_aws_serverlessapplicationrepository_application.go
	modified:   aws/table_aws_wellarchitected_answer.go
	modified:   aws/table_aws_wellarchitected_check_detail.go
	modified:   aws/table_aws_wellarchitected_check_summary.go
	modified:   aws/table_aws_wellarchitected_consolidated_report.go
	modified:   aws/table_aws_wellarchitected_lens.go
	modified:   aws/table_aws_wellarchitected_lens_review.go
	modified:   aws/table_aws_wellarchitected_lens_review_improvement.go
	modified:   aws/table_aws_wellarchitected_lens_review_report.go
	modified:   aws/table_aws_wellarchitected_lens_share.go
	modified:   aws/table_aws_wellarchitected_milestone.go
	modified:   aws/table_aws_wellarchitected_notification.go
	modified:   aws/table_aws_wellarchitected_share_invitation.go
	modified:   aws/table_aws_wellarchitected_workload.go
	modified:   aws/table_aws_wellarchitected_workload_share.go
	modified:   go.mod
	modified:   go.sum
```

**Comment by Zlender** [comment]
Split out the aws updated to #2039

**Comment by misraved** [comment]
Thanks @Zlender for making the changes and I apologize for the radio silence on this PR.

The updates made in https://github.com/turbot/steampipe-plugin-aws/pull/2039 must be tested thoroughly before we can add the updates to the main branch. Could you please resolve the merge conflicts in this PR before we can merge it in `add-eks-insights-table` for further testing?

**Comment by Zlender** [comment]
@misraved conflicts resolved.

**Pull request merged**
