### PR TITLE
Add profile from aws spc

### PR DESCRIPTION
**Pull request by dbmurphy**
Extends aws_account to include account_profile column which is pulled get GetConfig from the spc file. This can be useful if someone wants to  join on account and display account_profile vs account_aliases if they don't have aliases defined in AWS. 

# Example query results
<details>
  <summary>Results</summary>
  
```
> select account_id,account_profile from aws_all.aws_account
+---------------+-------------------+
| account_id    | account_profile   |
+---------------+-------------------+
| 000000000000  | shared-services   |
| 000000000001  | nonprod           |
| 000000000002  | prod              |
+---------------+-------------------+

```
</details>

### CODE REVIEW

**Comment by rajlearner17** [comment]
@dbmurphy **Appreciate** for the PR. This seems an interesting suggestion, we will test it and discuss it internally before taking appropriate steps.

**Comment by rajlearner17** [comment]
@dbmurphy while I was trying without specifying any connection name as below, I got the error, should we expect a `default` profile to return as per this [line](https://github.com/turbot/steampipe-plugin-aws/blob/c8154a2a28a969678a61ba04c3c20f1a7eb2f8d9/aws/common_columns.go#L115)?
Maybe we need to test, how this behaves when we set the profile with environment variables?

```
> select account_id,account_profile from aws_account
Error: rpc error: code = Internal desc = hydrate function listAccountAlias failed with panic runtime error: invalid memory address or nil pointer dereference (SQLSTATE HV000)
```

**Comment by dbmurphy** [comment]
Given I am only using the settings that already existed in the getConfig, this one is very odd. 

I suspect I know the issue, but doesn't seem like that follows normal AWS semantics...

```
	awsConfig := GetConfig(d.Connection)
	accountProfile := *awsConfig.Profile
	if accountProfile == "" {
		accountProfile = "default"
	}
```

I would expect any "profile" usage to assume default profile if it can't find one as that is how aws's cli works. However in this case it is possible the awsConfig object has no "Profile" property to find.  And maybe I need to restructure this to test for its existence, but as I understood it the awsConfig would always have Profile defined as an empty string. 

Is this me misunderstanding the expected the output of ConfigSchema and awsConfig Structs?

**Comment by dbmurphy** [comment]
I did some more digging, this is actually an existing issue this code does not cause but that it's showing in the testings...

```
Davids-MacBook-Pro:config dmurphy$ steampipe plugin list
+--------------------------------------------------+---------+--------------------------------------------------------------------------------------------------+
| Name                                             | Version | Connections                                                                                      |
+--------------------------------------------------+---------+--------------------------------------------------------------------------------------------------+
| hub.steampipe.io/plugins/turbot/aws@latest       | 0.42.2  | aws_digital_db_nonprod,aws_digital_db_prod,aws_digital_db_shared,aws_key,aws_legacy_prod,aws_all |
| hub.steampipe.io/plugins/turbot/steampipe@latest | 0.2.0   | steampipe                                                                                        |
+--------------------------------------------------+---------+--------------------------------------------------------------------------------------------------+
Davids-MacBook-Pro:config dmurphy$ steampipe query
Welcome to Steampipe v0.10.0
For more information, type .help
> select account_profile, account_id from aws_digital_db_nonprod.aws_account
+--------------------------+--------------+
| account_profile          | account_id   |
+--------------------------+--------------+
| XXXXXXXX-nonprod.XX.XXX  | 000000000000 |
+--------------------------+--------------+
> select account_profile, account_id from aws_key.aws_account
Error: rpc error: code = Internal desc = hydrate function listAccountAlias failed with panic runtime error: invalid memory address or nil pointer dereference
> 
````

**Comment by dbmurphy** [comment]
Updated the code so that during awsConfig setup, if awsConfig.Profile is nil , sets an empty string as the pointer source 

```
> select  account_profile,account_id from aws_key.aws_account
+-----------------+--------------+
| account_profile | account_id   |
+-----------------+--------------+
| default         | XXXXXXXXXXXX |
+-----------------+--------------+
```

Using:
```
connection "aws_key" {
  plugin      = "aws"
  access_key     = "XXXXXXXXXXXXXXXXXXXX"
  secret_key     = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
  regions     = ["eu-west-1"]
}
```

**Comment by rajlearner17** [comment]
@dbmurphy Nice to see this change 👍 . I will test this and get back, also will have this further checked by @cbruno10

**Comment by dbmurphy** [comment]
Additional mixed-mode testing by mixing SSO and Key modes in an aggregator: (SSO profile name and account_ids replaced for account safety.
```
> select account_profile,account_id from aws_test_account_key.aws_account
+------------------------+--------------+
| account_profile        | account_id   |
+------------------------+--------------+
| David Personal Profile | XXXXXXXXXXXX |
+------------------------+--------------+
> select account_profile,account_id from aws_test_db_prod.aws_account
+-----------------------+--------------+
| account_profile       | account_id   |
+-----------------------+--------------+
| David SSO Profile | YYYYYYYYYYYY |
+-----------------------+--------------+
> select account_profile,account_id from aws_test_all.aws_account
+------------------------+--------------+
| account_profile        | account_id   |
+------------------------+--------------+
| David Personal Profile | XXXXXXXXXXXX |
| David SSO Profile  | YYYYYYYYYYYY |
+------------------------+--------------+
> 
```

**Pull request closed without merging**
