### PR TITLE
Add table aws_organizations_policy. closes #1561

### LINKED ISSUE #1561: Add table aws_organizations_service_control_policy
AWS are due to deprecate several IAM actions by March 2023. I was hoping I could query a table to get a list of SCPs and the actual policy to help aid my investigation efforts.

### PR DESCRIPTION
**Pull request by ParthaI**
# Integration test logs
<details>
  <summary>Logs</summary>

```
N/A
```
</details>

# Example query results
<details>
  <summary>Results</summary>

```
> select
  name,
  id,
  content ->> 'Version' as policy_version,
  content ->> 'Statement' as policy_statement
from
  aws_organizations_service_control_policy
where
  type = 'SERVICE_CONTROL_POLICY';
+---------------+-----------------+----------------+-------------------------------------------------------+
| name          | id              | policy_version | policy_statement                                      |
+---------------+-----------------+----------------+-------------------------------------------------------+
| FullAWSAccess | p-FullAWSAccess | 2012-10-17     | [{"Action": "*", "Effect": "Allow", "Resource": "*"}] |
+---------------+-----------------+----------------+-------------------------------------------------------+

> select * from aws_organizations_service_control_policy where type = 'SERVICE_CONTROL_POLICY'
+---------------+-----------------+--------------------------------------------------------------------------+------------------------+-------------+----------------------------------+----------------------------+---------------+---------------------------------------->
| name          | id              | arn                                                                      | type                   | aws_managed | description                      | content                    | title         | akas                                   >
+---------------+-----------------+--------------------------------------------------------------------------+------------------------+-------------+----------------------------------+----------------------------+---------------+---------------------------------------->
| FullAWSAccess | p-FullAWSAccess | arn:aws:organizations::aws:policy/service_control_policy/p-FullAWSAccess | SERVICE_CONTROL_POLICY | true        | Allows access to every operation | {                          | FullAWSAccess | ["arn:aws:organizations::aws:policy/ser>
|               |                 |                                                                          |                        |             |                                  |   "Version": "2012-10-17", |               |                                        >
|               |                 |                                                                          |                        |             |                                  |   "Statement": [           |               |                                        >
|               |                 |                                                                          |                        |             |                                  |     {                      |               |                                        >
|               |                 |                                                                          |                        |             |                                  |       "Effect": "Allow",   |               |                                        >
|               |                 |                                                                          |                        |             |                                  |       "Action": "*",       |               |                                        >
|               |                 |                                                                          |                        |             |                                  |       "Resource": "*"      |               |                                        >
|               |                 |                                                                          |                        |             |                                  |     }                      |               |                                        >
|               |                 |                                                                          |                        |             |                                  |   ]                        |               |                                        >
|               |                 |                                                                          |                        |             |                                  | }                          |               |                                        >
+---------------+-----------------+--------------------------------------------------------------------------+------------------------+-------------+----------------------------------+----------------------------+---------------+---------------------------------------->

```
</details>

### CODE REVIEW

**Review by karanpopat — APPROVED** [review]
LGTM

**Comment by misraved** [comment]
@ParthaI @karanpopat  should we not add a canonical policy content column?

**Comment by karanpopat** [comment]
@misraved have added the column `policy_std`.

**Comment by misraved** [comment]
@karanpopat I don't see a `policy_std` column, has it been added?

**Comment by misraved** [comment]
@ParthaI @karanpopat For the design of this table, I feel we could implement the following:

- This table should be named as `aws_organizations_policy`, per https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/organizations_policy.
- Instead of using `type` as a `KeyColumn`, we should add it as an optional qual. This should be documented in the table docs page. Reference - https://docs.aws.amazon.com/organizations/latest/APIReference/API_ListPolicies.html
- When we keep the `content` column as `JSON`, note that as per the response syntax mentioned in https://docs.aws.amazon.com/organizations/latest/APIReference/API_Policy.html#organizations-Type-Policy-Content, are we able to query it? Should the column be named as `policy` to maintain consistency across all the tables?
- For canonicalizing the policy content, we should add another column `policy_std` so that the contents of the policy can be queried easily. Please refer https://github.com/turbot/steampipe-plugin-aws/blob/main/aws/table_aws_ecr_repository.go#L125 for more information

**Comment by ParthaI** [comment]
> 

@misraved I have updated the table as per this comment, here is an update 

- Updated the table name to `aws_organizations_policy` as per the terraform doc.
- As per the [API](https://docs.aws.amazon.com/organizations/latest/APIReference/API_ListPolicies.html) the `Policy Type` is a required parameter so we can not use the `type` column as optional quals in list config we must need to pass the policy type value before making API call.
- The column `content` does not provide the whole policy structure, It contains only policy version and policy statement of the policy. I do not think we should rename the column name to `policy`.
- In other tables we are getting the policy as a json string and we are converting it to a canonical form for easier searching (https://github.com/turbot/steampipe-plugin-aws/blob/main/aws/table_aws_ecr_repository.go#L125 ). In this table we have everything is in a structural form should we add as separate column(`policy_std`)?

**Review by misraved — APPROVED** [review]

**Pull request merged**
