### PR TITLE
Add table `aws_vpc_security_group_rules`

### PR DESCRIPTION
**Pull request by cjsrkd3321**
# Integration test logs
<details>
  <summary>Logs</summary>
  
```
$node --version
v16.13.2

$ node tint.js
No env file present for the current environment:  staging 
 Falling back to .env config
No env file present for the current environment:  staging
customEnv TURBOT_TEST_EXPECTED_TIMEOUT undefined

SETUP: tests/aws_vpc_security_group_rules []

PRETEST: tests/aws_vpc_security_group_rules

TEST: tests/aws_vpc_security_group_rules
Running terraform

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # aws_security_group.named_test_resource will be created
  + resource "aws_security_group" "named_test_resource" {
      + arn                    = (known after apply)
      + description            = "Test Security Group."
      + egress                 = (known after apply)
      + id                     = (known after apply)
      + ingress                = (known after apply)
      + name                   = "turbottest18134"
      + name_prefix            = (known after apply)
      + owner_id               = (known after apply)
      + revoke_rules_on_delete = false
      + tags                   = {
          + "name" = "turbottest18134"
        }
      + tags_all               = {
          + "name" = "turbottest18134"
        }
      + vpc_id                 = (known after apply)
    }

  # aws_security_group_rule.ingress will be created
  + resource "aws_security_group_rule" "ingress" {
      + cidr_blocks              = [
          + "10.0.0.0/16",
        ]
      + description              = "TLS from VPC"
      + from_port                = 443
      + id                       = (known after apply)
      + protocol                 = "tcp"
      + security_group_id        = (known after apply)
      + self                     = false
      + source_security_group_id = (known after apply)
      + to_port                  = 443
      + type                     = "ingress"
    }

  # aws_vpc.main will be created
  + resource "aws_vpc" "main" {
      + arn                                  = (known after apply)
      + cidr_block                           = "10.0.0.0/16"
      + default_network_acl_id               = (known after apply)
      + default_route_table_id               = (known after apply)
      + default_security_group_id            = (known after apply)
      + dhcp_options_id                      = (known after apply)
      + enable_classiclink                   = (known after apply)
      + enable_classiclink_dns_support       = (known after apply)
      + enable_dns_hostnames                 = (known after apply)
      + enable_dns_support                   = true
      + id                                   = (known after apply)
      + instance_tenancy                     = "default"
      + ipv6_association_id                  = (known after apply)
      + ipv6_cidr_block                      = (known after apply)
      + ipv6_cidr_block_network_border_group = (known after apply)
      + main_route_table_id                  = (known after apply)
      + owner_id                             = (known after apply)
      + tags                                 = {
          + "name" = "turbottest18134"
        }
      + tags_all                             = {
          + "name" = "turbottest18134"
        }
    }

Plan: 3 to add, 0 to change, 0 to destroy.

Changes to Outputs:
  + account_id     = "111111111111"
  + ingress_sgr_id = (known after apply)
  + resource_aka   = (known after apply)
  + resource_id    = (known after apply)
  + resource_name  = "turbottest18134"
  + vpc_id         = (known after apply)
aws_vpc.main: Creating...
aws_vpc.main: Still creating... [10s elapsed]
aws_vpc.main: Creation complete after 10s [id=vpc-0fdbd8db678c3b7e7]
aws_security_group.named_test_resource: Creating...
aws_security_group.named_test_resource: Creation complete after 7s [id=sg-00056b3f3b3e3920a]
aws_security_group_rule.ingress: Creating...
aws_security_group_rule.ingress: Creation complete after 3s [id=sgrule-1626592594]

Warning: Deprecated Resource

  with data.null_data_source.resource,
  on variables.tf line 45, in data "null_data_source" "resource":
  45: data "null_data_source" "resource" {

The null_data_source was historically used to construct intermediate values
to re-use elsewhere in configuration, the same can now be achieved using
locals

(and one more similar warning elsewhere)

Apply complete! Resources: 3 added, 0 changed, 0 destroyed.

Outputs:

account_id = "111111111111"
ingress_sgr_id = "sgrule-1626592594"
resource_aka = "arn:aws:ec2:us-east-1:111111111111:security-group/sg-00056b3f3b3e3920a"
resource_id = "sg-00056b3f3b3e3920a"
resource_name = "turbottest18134"
vpc_id = "vpc-0fdbd8db678c3b7e7"
Template Error: undefined
The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object

ERROR DETECTED: Stopping test run and entering teardown phase.
The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object

TEARDOWN: tests/aws_vpc_security_group_rules

SUMMARY:

1/1 passed.
```
</details>

# Example query results
<details>
  <summary>Results</summary>
  
```
> select group_id, security_group_rule_id, from_port, to_port, ip_protocol, description, cidr_ipv4, arn, title  from aws_vpc_security_group_rules
+----------------------+------------------------+-----------+---------+-------------+-------------+-------------------+-----------------------------------------------------------------------------------+------------------------------------------------------------+
| group_id             | security_group_rule_id | from_port | to_port | ip_protocol | description | cidr_ipv4         | arn                                                                               | title                                                      |
+----------------------+------------------------+-----------+---------+-------------+-------------+-------------------+-----------------------------------------------------------------------------------+------------------------------------------------------------+
| sg-00000000000000000 | sgr-02e4ca1ee06752c83  | -1        | -1      | icmp        | <null>      | 0.0.0.0/0         | arn:aws:ec2:ap-northeast-2:111111111111:security-group-rule/sgr-02e4ca1ee06752c83 | sgr-02e4ca1ee06752c83_egress_icmp_-1_-1_0.0.0.0/0          |
| sg-00000000000000000 | sgr-0714c4511e7ae422d  | -1        | -1      | -1          | <null>      | 0.0.0.0/0         | arn:aws:ec2:ap-northeast-2:111111111111:security-group-rule/sgr-0714c4511e7ae422d | sgr-0714c4511e7ae422d_ingress_-1_-1_-1_0.0.0.0/0           |
| sg-01111111111111111 | sgr-02485a92cd6ff6c15  | -1        | -1      | -1          | <null>      | 0.0.0.0/0         | arn:aws:ec2:ap-northeast-2:111111111111:security-group-rule/sgr-02485a92cd6ff6c15 | sgr-02485a92cd6ff6c15_ingress_-1_-1_-1_0.0.0.0/0           |
| sg-00000000000000000 | sgr-0ad7ff1d9d627d82f  | -1        | -1      | -1          | <null>      | <null>            | arn:aws:ec2:ap-northeast-2:111111111111:security-group-rule/sgr-0ad7ff1d9d627d82f | sgr-0ad7ff1d9d627d82f_egress_-1_-1_-1_::/0                 |
| sg-02222222222222222 | sgr-0c65a372537609bdb  | -1        | -1      | -1          | <null>      | 2.2.2.2/32        | arn:aws:ec2:ap-northeast-2:111111111111:security-group-rule/sgr-0c65a372537609bdb | sgr-0c65a372537609bdb_egress_-1_-1_-1_218.50.139.169/32    |
| sg-00000000000000000 | sgr-050992310bfc7508c  | -1        | -1      | icmpv6      | <null>      | <null>            | arn:aws:ec2:ap-northeast-2:111111111111:security-group-rule/sgr-050992310bfc7508c | sgr-050992310bfc7508c_egress_icmpv6_-1_-1_::/0             |
| sg-02222222222222222 | sgr-0214fd8884a465a07  | -1        | -1      | -1          | <null>      | 0.0.0.0/0         | arn:aws:ec2:ap-northeast-2:111111111111:security-group-rule/sgr-0214fd8884a465a07 | sgr-0214fd8884a465a07_egress_-1_-1_-1_0.0.0.0/0            |
| sg-01111111111111111 | sgr-0eee13951944c6b2d  | 3389      | 3389    | tcp         | asdf        | 1.1.1.1/32        | arn:aws:ec2:ap-northeast-2:111111111111:security-group-rule/sgr-0eee13951944c6b2d | sgr-0eee13951944c6b2d_egress_tcp_3389_3389_1.1.1.1/32      |
| sg-02222222222222222 | sgr-02fd2f97af5b64749  | -1        | -1      | -1          | <null>      | <null>            | arn:aws:ec2:ap-northeast-2:111111111111:security-group-rule/sgr-02fd2f97af5b64749 | sgr-02fd2f97af5b64749_egress_-1_-1_-1_sg-02222222222222222 |
| sg-02222222222222222 | sgr-0297fd188572ff485  | -1        | -1      | -1          | <null>      | 0.0.0.0/0         | arn:aws:ec2:ap-northeast-2:111111111111:security-group-rule/sgr-0297fd188572ff485 | sgr-0297fd188572ff485_ingress_-1_-1_-1_0.0.0.0/0           |
| sg-00000000000000000 | sgr-045c2ece99018db86  | 0         | 65535   | tcp         | rextest     | <null>            | arn:aws:ec2:ap-northeast-2:111111111111:security-group-rule/sgr-045c2ece99018db86 | sgr-045c2ece99018db86_egress_tcp_0_65535_::/0              |
| sg-00000000000000000 | sgr-0477dfb205c83dcb3  | 0         | 65535   | udp         | <null>      | 0.0.0.0/0         | arn:aws:ec2:ap-northeast-2:111111111111:security-group-rule/sgr-0477dfb205c83dcb3 | sgr-0477dfb205c83dcb3_egress_udp_0_65535_0.0.0.0/0         |
+----------------------+------------------------+-----------+---------+-------------+-------------+-------------------+-----------------------------------------------------------------------------------+------------------------------------------------------------+
```
</details>

### CODE REVIEW

**Comment by rajlearner17** [comment]
@cjsrkd3321 Thank you for using Steampipe and good to see this update PR which is using a separate API than the existing [table](https://hub.steampipe.io/plugins/turbot/aws/tables/aws_vpc_security_group_rule) approach. We will be evaluating this. 
Just curious to know, did you find the current table [aws_vpc_security_group_rule](https://hub.steampipe.io/plugins/turbot/aws/tables/aws_vpc_security_group_rule) not catering any data as expected or any other observation?

**Comment by cjsrkd3321** [comment]
> 

Hello. first, thanks for your reply. I need a 'sgr-*' column but the existing table was not. Of course, I tried to update the existed table(aws_vpc_security_group_rule) but I thought it wasn't the right way. For example, I checked our AWS account's SG vulnerability. And I asked the people in charge for action.
But, they were confused that "is this rule right?". So, I wrote and PR this code. 

I don't know if you understood because my English is not good enough. If you need any additional information, please let me know.

**Comment by rajlearner17** [comment]
@cjsrkd3321 Thanks for the quick response, understand that your team has confusion, sorry for the inconvenience.  
If I understand correctly, after analyzing the new table columns with the current table, we find only an additional column is **`security_group_rule_id`**, is this the only column you are looking for to have? or is something I am missing to interpret?

As per the image attached 

image

**Comment by cjsrkd3321** [comment]
Yes. That's right. And I created a new table to follow the new API(DescribeSecurityGroupRules) form.

**Comment by cbruno10** [comment]
Hey @cjsrkd3321 , thanks for opening this PR! We really like the changes you made in this PR, especially using the API to get the VPC security group rules directly. We believe this is better than how we're doing it in our current `aws_vpc_security_group_rule` table, so we're updating our `aws_vpc_security_group_rules` table in this [PR](https://github.com/turbot/steampipe-plugin-aws/pull/860) to make similar API calls to what you've done in this PR (so the  `security_group_rule_id` column would also be added as well).

We decided to update our existing table instead of adding a new one alongside it because we'd like to keep just 1 table in this plugin to represent VPC security group rules, so we won't merge in this PR, but would like to thank you for the direction you provided here.

If you have time, please try out using the updated `aws_vpc_security_group_rule` table in the `rules` branch and let us know if this satisfies your requirements. If you have any feedback on the changes, please let us know in that PR as well!

**Pull request closed without merging**
