### PR TITLE
Update AWS libraries

### PR DESCRIPTION
**Pull request by Zlender**
This is in response to comment #2035. My go skills are basic so if I made a silly mistake or went against standard way of doing it let me know.
# Integration test logs
<details>
  <summary>Logs</summary>

```
Add passing integration test logs here
```
</details>

# Example query results
<details>
  <summary>Results</summary>

```
Add example SQL query results here (please include the input queries as well)
```
</details>

### CODE REVIEW

**Comment by Zlender** [comment]
This currently does not compile. It looks like 1.4.0 version of securitylake library removes GetDatalake api call https://github.com/aws/aws-sdk-go-v2/commit/c6827664f33491268f19387989b8b948a3a99199

**Comment by Zlender** [comment]
Found https://docs.aws.amazon.com/security-lake/latest/APIReference/API_ListDataLakes.html . It compiles now but likely doesn't work correctly yet.

**Comment by bigdatasourav** [comment]
Hey @Zlender, Could you please resolve the conflicts?

**Comment by Zlender** [comment]
@bigdatasourav done

**Pull request merged**
